# github_project: redmine_project
---
theforeman/foreman: foreman
theforeman/smart-proxy: smart-proxy
theforeman/foreman_chef: chef
theforeman/foreman-docker: docker
theforeman/foreman_ansible: ansible
theforeman/foreman_azure: azure
theforeman/foreman-digitalocean: digitalocean
theforeman/foreman-selinux: selinux
theforeman/foreman-tasks: foreman-tasks
theforeman/foreman_openscap: foreman_openscap
theforeman/smart_proxy_chef: chef
theforeman/smart_proxy_dynflow: foreman_remote_execution
theforeman/smart_proxy_openscap: smart-proxy-openscap
theforeman/smart_proxy_remote_execution_ssh: foreman_remote_execution
theforeman/foreman_remote_execution: foreman_remote_execution
Katello/katello: katello
Katello/hammer-cli-katello: katello
Katello/bastion: bastion
Katello/katello-installer: katello
